[profile.default]
optimizer = true
optimizer-runs = 1
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"

[rpc_endpoints]
arbitrum_goerli = "${ARB_GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
